const GET_DATA = 'GET_DATA';
const FILTER_DATA = 'FILTER_DATA';
const SORT_DATA = 'SORT_DATA';
const START_FETCHING = 'START_FETCHING';
const STOP_FETCHING = 'STOP_FETCHING';
const SET_STATE_FROM_INPUTS = 'SET_STATE_FROM_INPUTS';
const SEND_DATA = 'SEND_DATA';
const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
const SET_MESSAGE = 'SET_MESSAGE';
const SET_CLASSNAME = 'SET_CLASSNAME';

export {
  GET_DATA,
  FILTER_DATA,
  SORT_DATA,
  START_FETCHING,
  STOP_FETCHING,
  SET_STATE_FROM_INPUTS,
  SET_MESSAGE,
  SET_CLASSNAME,
  HIDE_NOTIFICATION,
  SHOW_NOTIFICATION,
  SEND_DATA,
};
